### ISSUE TITLE
System.ObjectDisposedException: Cannot access a closed Stream.

### ISSUE THREAD

**Issue by hoainamctin** [icsharpcode/SharpZipLib#161] opened 2017-01-11 06:25 UTC
### Steps to reproduce
                ZipEntry ze = zip.GetEntry(filePath);
                if (ze == null)
                    return null;
                ms = new MemoryStream();
                zip.GetInputStream(ze).CopyTo(ms);
                ms.Position = 0;
                return ms;
(zip is ZipFile variable)

### Expected behavior
Can handle the exception

### Actual behavior
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.TestLocalHeader(ZipEntry entry, HeaderTest tests)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(Int64 entryIndex)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)

### Version of SharpZipLib
0.86.0 (the latest version currently on NuGet).

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [x] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by piksel** [comment] 2018-05-12 16:55
Unable to reproduce in latest nuget packages, so I am closing this.

**Closed by piksel** 2018-05-12 16:55 UTC
