### ISSUE TITLE
Extract zip file when it's made from Unix

### ISSUE THREAD

**Issue by davidbalonso** [icsharpcode/SharpZipLib#157] opened 2016-12-12 09:39 UTC
### Steps to reproduce
1. Try to unzip a file that it's made from Unix host
2. The code returns an exception "Version required to extract this entry not supported (788)"

### Expected behavior
I'm not sure that this is an error or if it's normal behavior, but I do not know why it doesn't work with this zip file version.

### Actual behavior
 It produces and exception "Version required to extract this entry not supported (788)"

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [X] Downloaded DLL from -> https://icsharpcode.github.io/SharpZipLib/
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by hahoyer** [comment] 2017-02-09 13:28
Got this error too. 
Please find a VS2015-solution that will reproduce the problem.
[Error788.zip](https://github.com/icsharpcode/SharpZipLib/files/763776/Error788.zip)

**Comment by guinaldi** [comment] 2017-06-01 20:51
Hello. Got this error too with Linux/Unix .zip generated file.
Any news about this issue?

Thank you

**Comment by Sigma88** [comment] 2017-12-14 14:21
I'm having this issue as well

I was wondering if anyone came across a solution/workaround to this

If there is anything I can provide to help debug this issue please let me know

**Comment by ivonin** [comment] 2017-12-14 14:46
@Sigma88 if I'm correct, the issue is fixed in source code but NuGet package is outdated. We ended up forking the project and building our own version of the package.

**Comment by Sigma88** [comment] 2017-12-14 17:22
@ivonin is your version available somewhere? I tried messing around with nuget but I'm not very familiar with it

**Comment by ivonin** [comment] 2017-12-14 20:48
@Sigma88 you can always just clone the repository, build it yourself and reference it the good old way (as a dll).

**Comment by Sigma88** [comment] 2017-12-14 22:19
@ivonin yeah that's what I did, I cloned the repo and built the project ( ICSharpCode.SharpZipLib.dll )
and then used that as a reference for my own project

the problem is that I'm still getting this error while trying to unzip an archive made on linux (the person who provided the archive wasn't more specific on the OS)

**Comment by Sigma88** [comment] 2017-12-15 10:04
actually, I have tried again and my project can't accept the current library as a reference, it complains about:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'Stream' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

which leads me to believe the new code is not compatible with .NET 3.5 ?

which is basically the only reason why I wanted to use this library in the first place 🤔

**Comment by piksel** [comment] 2018-05-12 16:48
Fixed in the >=1.0 nuget packages.

**Closed by piksel** 2018-05-12 16:48 UTC

**Comment by marcolbx** [comment] 2020-03-19 15:06
I solved this issue by doing the following workaround, if anyone has installed a previous version like me and keeps on getting this error: 
[Workaround]:
1) Unzip manually the file. 
2) Zip all files again from your computer.
3) Run your app.  //It worked for me because the problem was in the zip compression of the other persons computer.

**Comment by jluisnolasco** [comment] 2021-12-14 11:51
> 2\. 788)

Could you please specify the PR that fixed this issue?

**Comment by piksel** [comment] 2021-12-14 13:56
No, a quick git blame just shows a merge from a previous maintainer. I don't really understand what was going on with the repo at that time...
