### ISSUE TITLE
SharpZipLib "Cannot be less than zero"

### ISSUE THREAD

**Issue by naradasu74** [icsharpcode/SharpZipLib#204] opened 2017-12-05 19:50 UTC
### Steps to reproduce
Trying to extract tar.gz file with 15 files in it and total size of tar file is 413MB

I'm trying to use the below sample code I found 

public void ExtractTarGZipSample(string gzipFileName, string targetDir)
        {

            Stream inStream = File.OpenRead(gzipFileName);
            Stream gzipStream = new GZipInputStream(inStream);
            TarArchive tarArchive = TarArchive.CreateInputTarArchive(gzipStream);
            tarArchive.ExtractContents(targetDir);
            tarArchive.Close();
            gzipStream.Close();
        }

### Expected behavior
It should actually extract files to a destination directory from tar archive

### Actual behavior
It is throwing exception 

An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in Console-SampleApps.exe

Additional information: Cannot be less than zero

###Stack trace
   at ICSharpCode.SharpZipLib.Tar.TarHeader.set_Size(Int64 value)
   at ICSharpCode.SharpZipLib.Tar.TarHeader.ParseBuffer(Byte[] header)
   at ICSharpCode.SharpZipLib.Tar.TarInputStream.GetNextEntry()
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractContents(String destinationDirectory)
   at Console_SampleApps.Program.ExtractTarGZipSample(String gzipFileName, String targetDir) in C:\Users\Projects\Console-SampleApps\Console-SampleApps\Program.cs:line 94
   at Console_SampleApps.Program.Main() in C:\Users\Projects\Console-SampleApps\Console-SampleApps\Program.cs:line 58
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Obtained from (place an x between the brackets for all that apply)
- I'm using v0.86.0
- Package installed using:
 - [ ] NuGet

**Comment by piksel** [comment] 2018-05-13 11:18
Could not reproduce using a sample .tar.gz and the latest version.
Either there is something in your input file or it has been fixed in the later versions (>=1.0).

I'm closing this, but if you still have the problem, try with the latest version and a simple archive that you can upload here for testing.

**Closed by piksel** 2018-05-13 11:18 UTC
