### ISSUE TITLE
Unzip the compressed zip under mac

### ISSUE THREAD

**Issue by 5chn** [icsharpcode/SharpZipLib#342] opened 2019-05-07 13:04 UTC
Hello, author, would you like to ask your SharpZipLib.dll package to extract the zip package compressed by mac? Have you ever encountered a zip package that is compressed under the mac, and the zero-byte file is coming out.

**Comment by 5chn** [comment] 2019-05-07 13:19
I use the zip package made by mac computer, and then use C# SharpZipLib.dll to extract the zip of this mac, get the result of zero byte file, the file should not be zero byte.

**Comment by piksel** [comment] 2019-05-22 16:02
Hello! Please use the issue template when creating an issue like this.
What version of SharpZipLib are you using? What version of .NET?
Could you provide the code that you used to extract the contents?
How was the file created, using what software on macOS?

**Comment by 5chn** [comment] 2019-05-23 08:41
sharpZipLib version is 0.86.0.518, .NET version is Unity 3.5 .net Subset Base Class Libraries.
extract code:
var zipFile = File.OpenRead(m_currentUnzipItem.SrcZipFile);
                        m_currentUnzipItem.totalSize = (int)zipFile.Length;
                        ZipInputStream unzipStream = new ZipInputStream(zipFile);
                        try
                        {
                            if (m_unzipProcessList.IndexOf(m_currentUnzipItem) < 0)
                            {
                                m_unzipProcessList.Add(m_currentUnzipItem);
                            }
                            ZipEntry theEntry;
                            while ((theEntry = unzipStream.GetNextEntry()) != null)
                            {
                                //先创建目录
                                string fullName = m_currentUnzipItem.ToDir + theEntry.Name;
                                string dir = Path.GetDirectoryName(fullName);

                                if (!Directory.Exists(dir))
                                {
                                    Directory.CreateDirectory(dir);
                                }
                                Debuger.Log("file={0}, dir={1}", theEntry.Name, dir);
                                if (theEntry.IsFile)
                                {
                                    if (File.Exists(fullName))
                                    {//删除原有文件
                                     //File.Delete(fullName);
                                    }
                                    FileStream streamWriter = File.Create(fullName);
                                    try
                                    {
                                        //unzipStream.Seek(theEntry.Offset, SeekOrigin.Begin);
                                        int readTotalLen = 0;
                                        while (readTotalLen < theEntry.Size)
                                        {
                                            Array.Clear(UnzipBuffer, 0, UnzipBuffer.Length);
                                            int readlen = unzipStream.Read(UnzipBuffer, 0, UnzipBuffer.Length);
                                            readTotalLen += readlen;
                                            streamWriter.Write(UnzipBuffer, 0, readlen);
                                            streamWriter.Flush();
                                            m_currentUnzipItem.unzipedSize = (int)zipFile.Position;
                                            //Debuger.Log("unzip={0}, total={1}, m_currentUnzipItem.stopUnzip:{2}", m_currentUnzipItem.unzipedSize, m_currentUnzipItem.totalSize, m_currentUnzipItem.stopUnzip);
                                            if (m_currentUnzipItem.stopUnzip)
                                            {
                                                break;
                                            }
                                        }
                                    }
                                    catch (Exception ex)
                                    {
                                        Debuger.Error("解压出错1:{0},{1}", m_currentUnzipItem.SrcZipFile, ex.ToString());
                                        m_currentUnzipItem.errorCode = ZipErrorCode.SingleFileError;

                                    }
                                    streamWriter.Close();
                                    streamWriter.Dispose();
                                }
                                if (m_currentUnzipItem.stopUnzip)
                                {
                                    break;
                                }
                            }
                        }
                        catch(Exception ext)
                        {
                            Debuger.Error("解压出错2:{0},{1}", m_currentUnzipItem.SrcZipFile, ext.ToString());
                            m_currentUnzipItem.errorCode = ZipErrorCode.ZipFileError;
                        }

Compressed files by default zip mode on MAC computer, right-click file name, create compressed files

**Comment by 5chn** [comment] 2019-05-23 09:09
> 你好！创建此类问题时请使用问题模板。
> 您使用的是什么版本的SharpZipLib？什么版本的.NET？
> 你能提供用于提取内容的代码吗？
> 如何使用macOS上的软件创建文件？

**Comment by Numpsy** [comment] 2019-05-23 12:43
>>> The problem is unzipStream. GetNextEntry (). size is - 1L;

Can that happen if the archive is using Zip64? (I couldn't say offhand if the macOS zip tool produces those)

**Comment by piksel** [comment] 2019-05-23 13:55
Yeah, this seems related to Zip64. Are you able to try the latest package? I'm not too familiar with using packages in unity, but I think the lastest version should support .NET standard.

**Comment by 5chn** [comment] 2019-05-24 02:00
The latest version does not have DLL packages

**Comment by 5chn** [comment] 2019-05-24 03:16
Can you give me a latest version of the DLL package? I can't install the nupkg file. Thank you.

**Comment by Numpsy** [comment] 2019-05-24 10:29
The nupkg is just a zip file, you should be able to just extract it and copy the dlls out of it.

**Comment by piksel** [comment] 2019-06-18 19:43
Probably caused by #357

**Comment by piksel** [comment] 2020-11-10 18:45
Closing this as it should have been fixed in latest release.

**Closed by piksel** 2020-11-10 18:45 UTC
Labels: question
