### ISSUE TITLE
"Stream does not support writing" exception thrown when adding file to existing zip.

### ISSUE THREAD

**Issue by Grunkles** [icsharpcode/SharpZipLib#273] opened 2018-09-19 14:42 UTC
Preface: This is being done in LabVIEW from National Instruments (NI) using a third party library to access the .NET assembly so posting source code will be difficult. I will do my best to translate from LabVIEW to C#. I'm not proficient with C# but have enough experience with C/C++/Java etc. to navigate the SZL source code. I recognize that this isn't a LabVIEW support forum but the issue seems to be happening inside of the library itself, so I'm here looking for help in understanding what can cause the exception to be thrown.

### Steps to reproduce
1. Create new Zip file using ZipFile.Create(String) and UseZip64 (ON).
![zipfile open](https://user-images.githubusercontent.com/43388823/45761156-abe59200-bbf9-11e8-8569-82523b655bc5.png)
Here's a quick legend for what you're looking at.
 * Wrench icons are properties, cheese wedges(?) are constructors, dashed arrows are methods.
 * The white blocks under the yellow "Headers" are the property/method parameters.
![zipfile create](https://user-images.githubusercontent.com/43388823/45761205-c4ee4300-bbf9-11e8-9ac6-c3f85e21e360.PNG) is the same as ZipFile.Create(FileName)
 * The colored lines are visual representations of passing variables. 
 * Data flows from left to right along the lines like a flow chart. 
 * All inputs on a block (left side) must have data "waiting" before the property/method is called, so there is no chance of a race condition if something is farther down the flow chart.
 * Teal lines are file/object references.
 * Blue lines are integers.
 * Pink lines are strings.
 * Gold lines are errors/exceptions.
2. Add files using ZipFile.Add(IStaticDataSource, String, CompressionMethod).
![zipfile error](https://user-images.githubusercontent.com/43388823/45758425-91101f00-bbf3-11e8-8238-0812e43078b8.png)
3. Close Zip file.
4. Re-open existing Zip file to add new files.
5. List contents of Zip file using ZipFile.get_EntryByIndex(index).
6. Make array of contents using ZipEntry.Name.
7. Check array of contents for matches so that only new files are added to Zip file.
8. Add new files using ZipFile.Add(IStaticDataSource, String, CompressionMethod) using same code above.
9. Call CommitUpdate to push data to Zip file
![zipfile commitupdate](https://user-images.githubusercontent.com/43388823/45761295-f36c1e00-bbf9-11e8-8018-9a8bcc6046c4.PNG) is the same as ZipFile.CommitUpdate().

### Expected behavior
New files should be added to the archive without errors.

### Actual behavior
Adding the first file gets up to ZipFile.CommitUpdate() and throws a "Stream does not support writing" exception. Looking at the source code, that exception (System.NotSupportedException) is thrown by an overloaded version of [Write()](https://github.com/icsharpcode/SharpZipLib/blob/0008e715ea08e17163bd3eb63d9e4a9e048ad962/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L3577). I haven't been able to nail down the exact call chain that ends up at Write() but on my end there are no errors thrown until CommitUpdate() is called. I can't debug any deeper in LabVIEW than the 

### Version of SharpZipLib
Version=0.86.0.518

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [X] DLL included as part of MGI library for LabVIEW (http://sine.ni.com/nips/cds/view/p/lang/en/nid/209753). I've attempted to contact MGI directly but have not received any response. I have a thread on the NI forums but since this is a third party package using an open source library, NI will probably not be able to help.
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

Thank you in advance!

**Comment by Grunkles** [comment] 2018-09-25 13:50
Any chance that this is caused by my antivirus software? We use CylancePROTECT here at work. Not sure if it actively monitors zip files for manipulation or not, but it's something to investigate.

**Comment by piksel** [comment] 2018-10-13 15:08
@Grunkles Unfortunately this is not a scenario I can reproduce. It is also using the old version of the library that I am not familiar with. Sorry.

**Comment by Grunkles** [comment] 2018-12-12 15:03
Finally getting back around to this issue and figured I'd try the 1.0 release. I don't have a way to compile it from source and can't install the .nuget package manager due to IT policies. Will a .dll ever be released for this?

**Comment by piksel** [comment] 2020-11-22 14:39
This unfortunately seems to be caused by something outside the scope of the library and there's been no updates on this ticket for a long time. Closing this.

**Closed by piksel** 2020-11-22 14:39 UTC
Labels: third-party
