### ISSUE TITLE
Compatibility SharpZipLib 0.86.0.518 with 7Zip 9.20

### ISSUE THREAD

**Issue by wkeilholz** [icsharpcode/SharpZipLib#126] opened 2016-07-27 12:23 UTC
I realize this is a somewhat weired question, but here it is:
I used an old version of SharpZipLib (0.84.0.0) to create lots of ZIP files. 
They open OK in 7zip 9.20.

Now I updated to SharpZipLib 0.860.518 (no changes to code) and again make lots of ZIPs... but they don't open with 7zip 9.20 anymore ('compression method not supported'). They open OK with 7zip 16.02. 

"Just update 7zip", you'll tell me. However, my ZIPs are fed into a complicated system of which I'm not sure how it goes about unzipping them - it might use 7zip 9.20. 

So the question is : is there a way to make the latest version of SharpZipLib (0.860.518 as of now) create ZIPs so they still open with 7zip 9.20? Does anybody know what has changed that might cause the problem?

I tried ICSharpCode.SharpZipLib.Zip.UseZip64.Off but no luck. Any other ideas?

Thanks,

Werner

### Steps to reproduce
1.Make a Zip with SharpZipLib 0.860.518
2.Try to unzip with  7zip 9.20

### Expected behavior
I'd like to unzip with 7zip 9.20 

### Actual behavior
Error 'compression method not supported'

### Version of SharpZipLib
0.860.518

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [X ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [ ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by gabisandor** [comment] 2016-08-08 09:54
I think your issue is related to mine: https://github.com/icsharpcode/SharpZipLib/issues/131. It looks like there are serious problems when it comes to SharpZipLib backwards compatibility.

Can you please tell me what compression level you're setting when creating the archives with the new SharpZipLib version?

**Comment by wkeilholz** [comment] 2016-08-08 11:40
Thanks for looking at this. The level used is 6 :
zipOutputStream.SetLevel(6);

**Comment by gabisandor** [comment] 2016-08-08 11:58
@wkeilholz In my issue (#131) the workaround with setting UseZip64 off worked for backwards compatibility with version 0.84. Are you sure you're setting it in the right place? It should be right after creating the ZipOutputStream, before writing any entry or file into the archive.

**Comment by wkeilholz** [comment] 2016-08-08 12:26
I just tried again, and no, it doesn't work even with 
ZipOutputStream s = new ZipOutputStream(File.Create(zipFileName));
s.UseZip64 = ICSharpCode.SharpZipLib.Zip.UseZip64.Off;

Note, however, that my case is more complicated, as it involves an outdated version of a third-party tool (7-zip 9.20). 

The 7-zip manager (9.20) is actually able to show the content of the archive, but attempts to unzip yield 'unknown compression method'. The problem may as well be on the 7-zip side (and fixed in the meantime in its latest version).

**Comment by gabisandor** [comment] 2016-08-08 13:09
@wkeilholz I see what you mean. You say 7Zip can show the content of the archives, can you check the properties of a file in the archive and see what's in the "Version" field? I think that value might give you a hint, there's a ZipFile class here in the GitHub repository with some version codes.

**Comment by wkeilholz** [comment] 2016-08-08 14:23
It says version 20 (method=deflate, host os=FAT32)

**Comment by McNeight** [comment] 2016-08-13 23:25
@wkeilholz 
Without knowing the specific internal workings of 7-Zip 9.20, and any changes that were made between it and 7-Zip 16.02, I don't know where the specific problem might be or how 7-Zip may have been fixed. Without that information, I don't know in what way SharpZipLib would have broken compatibility with 7-Zip 9.20 that was fixed with 7-Zip 16.02.

Because you are dependent on 7-Zip 9.20, I think the simplest answer for your application is to stick with SharpZipLib 0.84. It appears to be the most compatible for your application. If you want to dig into the internals of SharpZipLib, I've pointed out a few places where Zip64 support has varied in my response to #131 

If you come up with a fix that doesn't revert the current Zip64 defaults, please open up a pull request.

-Neil

**Closed by McNeight** 2016-08-13 23:25 UTC
Labels: documentation, wontfix, zip

**Comment by jfreilly** [comment] 2016-08-14 11:07
Zip archive formats are messy full stop.  There are many possible places
where things can go awry.  Worse much of the code handles special cases
were other existing code is wrong but tolerated so its even possible that
the problem is in handling of bad code rather than disagreeing on how
things should really be done.  In short Neils view that you should stick
with what works #Zip 0.84 and 7Z 9.20 is correct and the only workable
solution until/if the underlying issue is found.  Given the situation it
may not be found.

**Comment by jfreilly** [comment] 2016-08-14 11:15
Having said all that the simplest way it to compare the archives and see
what is different about them which is sometimes not very much.  It may
actually be easy to figure out whats going wrong.  I did have some code
that analysed ZIP archive in some detail that allowed that kind of thing to
be done which I might have lurking somewhere....

Is it possible to get working / non-working  files which have the same
contents so they can be looked at?  This brings up issues of size of the
archives and the sensitivity of the contents etc, but if its possible then
yeah lets have a look.
