### ISSUE TITLE
IndexOutOfRangeException on Dispose

### ISSUE THREAD

**Issue by monty241** [icsharpcode/SharpZipLib#373] opened 2019-08-09 19:31 UTC
### Reproduction

Not reproducible. Occurs every few weeks once in a user population of 8.000 companies.

When user cancels an action (thread abort), the ICSharpCode sometimes bails out with an IndexOutOfRangeException. Stack:

```
16:05:29.03102-41: !! First chance exception handling of type 'IndexOutOfRangeException':
16:05:29.03102-41: De index ligt buiten de matrixgrenzen.
16:05:29.03301-41: !! All stack traces:
16:05:29.03301-41: !!    bij System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   bij System.Environment.get_StackTrace()
   bij IBC.SBF.T()
   bij Invantive.Basics.ErrorConstants.GetEnvironmentStackTrace(Boolean ignoreErrors, String valueOnError)
   bij Invantive.Data.Error.CurrentDomain_FirstChanceException(Object sender, FirstChanceExceptionEventArgs e)
   bij ICSharpCode.SharpZipLib.Zip.Compression.DeflaterHuffman.TallyDist(Int32 distance, Int32 length) in C:\projects\sharpziplib\src\ICSharpCode.SharpZipLib\Zip\Compression\DeflaterHuffman.cs:regel 900
   bij ICSharpCode.SharpZipLib.Zip.Compression.DeflaterEngine.DeflateSlow(Boolean flush, Boolean finish) in C:\projects\sharpziplib\src\ICSharpCode.SharpZipLib\Zip\Compression\DeflaterEngine.cs:regel 814
   bij ICSharpCode.SharpZipLib.Zip.Compression.DeflaterEngine.Deflate(Boolean flush, Boolean finish) in C:\projects\sharpziplib\src\ICSharpCode.SharpZipLib\Zip\Compression\DeflaterEngine.cs:regel 129
   bij ICSharpCode.SharpZipLib.Zip.Compression.Deflater.Deflate(Byte[] output, Int32 offset, Int32 length) in C:\projects\sharpziplib\src\ICSharpCode.SharpZipLib\Zip\Compression\Deflater.cs:regel 478
   bij ICSharpCode.SharpZipLib.Zip.Compression.Streams.DeflaterOutputStream.Finish() in C:\projects\sharpziplib\src\ICSharpCode.SharpZipLib\Zip\Compression\Streams\DeflaterOutputStream.cs:regel 102
   bij ICSharpCode.SharpZipLib.GZip.GZipOutputStream.Finish() in C:\projects\sharpziplib\src\ICSharpCode.SharpZipLib\GZip\GzipOutputStream.cs:regel 183
   bij ICSharpCode.SharpZipLib.GZip.GZipOutputStream.Dispose(Boolean disposing) in C:\projects\sharpziplib\src\ICSharpCode.SharpZipLib\GZip\GzipOutputStream.cs:regel 148
   bij System.IO.Stream.Close()
   bij (Object )
   bij IBC.RA.T(Object )
   bij Invantive.Basics.CompressionUtility.CompressBytes(Byte[] oldBytes, Int32 compressionLevel)
   bij IBC.IA.T(Byte[] , Int32 )
   bij Invantive.Basics.HttpResponseCacheObject.set_ResponseTextBody(String value)
   bij (Object , String )
   bij IBC.OMF.T(Object , String )
   bij Invantive.Basics.HttpResponseCacheObject..ctor(String responseTextBody, Dictionary`2 responseHeaders, String url, String method, String requestTextBody, Nullable`1 compressionLevel, String id, String dataContainerId, String logOnCode)

```
On version 1.1.0, line 900 of TallyDist (not obfuscated), called from code like:

```cs
byte[] compressedBytes;

using (MemoryStream outputMemoryStream = new MemoryStream(memoryStreamSizeRounded))
{
    using (GZipOutputStream compressCompressionStream = new GZipOutputStream(outputMemoryStream))
    {
        compressCompressionStream.SetLevel(compressionLevel);
        compressCompressionStream.Write(oldBytes, 0, oldBytes.Length);
    }

    //
    // Get the compressed bytes from the output stream.
    //
    // Do not place this inside the using GZipOutputStream, because the output stream
    // will not be closed and you will be missing the end of the byte array.
    //
    compressedBytes = outputMemoryStream.ToArray();
}
```

### Expected behavior
No IndexOutOfRangeException

### Version of SharpZipLib
1.1.0

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

It is not critical, but confuses end users since the IndexOutOfRangeException bubbles up to them.

**Comment by piksel** [comment] 2019-08-21 19:46
Unfortunately calling [Thread.Abort](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort) is not supported and using it [will leave the library in an unknown state](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort#remarks).

**Comment by piksel** [comment] 2020-11-10 18:40
Closing this since it's hard to reproduce and therefore untestable (and should probably be handled in the consumer code anyway).

**Closed by piksel** 2020-11-10 18:40 UTC
