### ISSUE TITLE
Unzipping tar.gz flattens files to have no more than 1 directory

### ISSUE THREAD

**Issue by asdf23** [icsharpcode/SharpZipLib#165] opened 2017-01-20 23:00 UTC
I have a nested tar.gz file. I can extract these files using cygwin/tar no problem.
In SharpZipLib I'm doing the following:

```.cs
{
	// fileGitBlog is a FileInfo object pointing to tar.gz file
	using (Stream sourceStream = new GZipInputStream(fileGitBlob.OpenRead()))
	{
		using (TarArchive tarArchive = TarArchive.CreateInputTarArchive(sourceStream))
		{
			tarArchive.ExtractContents(@"c:\temp\somewhere\");
		}
	}
}
```
### Expected behavior
I expect to see the same results as cygwin, which is a directory structure populated with files
```
    SomeDir1\
    SomeDir1\SomeDir1a\
    SomeDir1\SomeDir1a\someFiles.txt
    SomeDir2\
    SomeDir2\SomeDir2a\someFiles.txt
```  

### Actual behavior
```
    SomeDir1\
    SomeDir1a\someFiles.txt
    SomeDir2\
    SomeDir2a\someFiles.txt
```

### Version of SharpZipLib
SharpZipLib 0.86.0

### Obtained from (place an x between the brackets for all that apply)
- Package installed using:
  - NuGet

**Comment by piksel** [comment] 2018-09-16 17:34
This seems odd. Nested directories should work. Could you provide a sample file?

**Comment by piksel** [comment] 2020-11-22 15:08
Closing this as unable to reproduce. Could be caused by #38/#338.

**Closed by piksel** 2020-11-22 15:08 UTC
Labels: needs-repro
