### ISSUE TITLE
DateTime in ZipEntry returns only even second values

### ISSUE THREAD

**Issue by deczaloth** [icsharpcode/SharpZipLib#224] opened 2018-04-13 22:59 UTC
### Steps to reproduce
1. Set the DateTime property of a ZipEntry to a DateTime whose seconds value is an even number:
`entry.DateTime = new DateTime(2018,04,14,15,30,11);`
2. if you try to get that value back you will get
`2018/04/14 15:30:10`
3. The same is true for any odd value for seconds.

### Expected behavior
You should get exactly the DateTime you set.

### Actual behavior
You get a DateTime whose seconds value is the biggest even number smaller that the actual value.

### Version of SharpZipLib
1.0.0-alpha2

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [x ] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

### Posible Solution
Surfing on the source i found that the definition of DateTime is ( SharpZipLib/src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs, l. 621):

```
public DateTime DateTime
		{
			get
			{
				uint sec = Math.Min(59, 2 * (dosTime & 0x1f));
				uint min = Math.Min(59, (dosTime >> 5) & 0x3f);
				uint hrs = Math.Min(23, (dosTime >> 11) & 0x1f);
				uint mon = Math.Max(1, Math.Min(12, ((dosTime >> 21) & 0xf)));
				uint year = ((dosTime >> 25) & 0x7f) + 1980;
				int day = Math.Max(1, Math.Min(DateTime.DaysInMonth((int)year, (int)mon), (int)((dosTime >> 16) & 0x1f)));
				return new System.DateTime((int)year, (int)mon, day, (int)hrs, (int)min, (int)sec);
			}
			set {
				var year = (uint)value.Year;
				var month = (uint)value.Month;
				var day = (uint)value.Day;
				var hour = (uint)value.Hour;
				var minute = (uint)value.Minute;
				var second = (uint)value.Second;

				if (year < 1980) {
					year = 1980;
					month = 1;
					day = 1;
					hour = 0;
					minute = 0;
					second = 0;
				} else if (year > 2107) {
					year = 2107;
					month = 12;
					day = 31;
					hour = 23;
					minute = 59;
					second = 59;
				}

				DosTime = ((year - 1980) & 0x7f) << 25 |
					(month << 21) |
					(day << 16) |
					(hour << 11) |
					(minute << 5) |
					(second >> 1);
			}
}
```
There is possible to see the root of the problem. The getter generates the value of seconds by multiplying by 2.
I corrected this simply by moving the bit shifting by one to the left on the assignment of DosTime, and then correcting this by bit shifting by one to the right on the getter. With this the multiplication by 2 is not needed:
```
public static DateTime DateTime
        {
            get
            {
                uint sec = Math.Min(59, (DosTime & 0x3f));
                uint min = Math.Min(59, (DosTime >> 6) & 0x3f);
                uint hrs = Math.Min(23, (DosTime >> 12) & 0x1f);
                uint mon = Math.Max(1, Math.Min(12, ((DosTime >> 22) & 0xf)));
                uint year = ((DosTime >> 26) & 0x7f) + 1980;
                int day = Math.Max(1, Math.Min(DateTime.DaysInMonth((int)year, (int)mon), (int)((DosTime >> 17) & 0x1f)));
                return new System.DateTime((int)year, (int)mon, day, (int)hrs, (int)min, (int)sec);
            }

            set
            {
                var year = (uint)value.Year;
                var month = (uint)value.Month;
                var day = (uint)value.Day;
                var hour = (uint)value.Hour;
                var minute = (uint)value.Minute;
                var second = (uint)value.Second;

                if (year < 1980)
                {
                    year = 1980;
                    month = 1;
                    day = 1;
                    hour = 0;
                    minute = 0;
                    second = 0;
                }
                else if (year > 2107)
                {
                    year = 2107;
                    month = 12;
                    day = 31;
                    hour = 23;
                    minute = 59;
                    second = 59;
                }

                DosTime = (year - 1980) << 26 |
                    (month << 22) |
                    (day << 17) |
                    (hour << 12) |
                    (minute << 6) |
                    (second);
            }
        }
```

I hope this could be solved soon as i am willing to include the SharpZipLib in my project!

Cheers and great work!

**Comment by piksel** [comment] 2018-05-12 10:58
It would make it incompatible with the zip file format though. It uses FAT/MS-DOS time, which has a resolution of 2 seconds.

**Comment by piksel** [comment] 2018-05-12 15:54
Closing this since it's working as intended.

**Closed by piksel** 2018-05-12 15:54 UTC
Labels: wontfix
