### ISSUE TITLE
I zip a directory, but a file which in zipped file has size 4,294,967,295

### ISSUE THREAD

**Issue by ShimizuShiori** [icsharpcode/SharpZipLib#215] opened 2018-02-24 06:45 UTC
### Steps to reproduce
1. use **ZipOutputStream** to zip a directory
2. dynamic create a **LOG FILE** to record the exceptions in zip process
3. when all files done, put the **LOG FILE** into **ZipOutputStream** via a **ZipEntry**

### Expected behavior
the zip file contains the **LOG FILE** and it can be opened

### Actual behavior
the zip file contains the **LOG FILE** but is can not be opened , because it's size is 4,294,967,295

### Version of SharpZipLib
0.86.0.518

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [x] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

---

ps. My English is poor, thank you for your attention

**Comment by piksel** [comment] 2018-05-12 11:12
The scenario seems a bit confusing, are you adding the log file that is actively being written to into the archive? That would certainly cause some issues.

Is the file on disk (before archiving) also the same size?

You can use software like [glogg](http://glogg.bonnefon.org/description.html) to view the contents of huge files.

**Comment by piksel** [comment] 2018-06-06 10:12
I am closing this as I am not able to reproduce. I'll reopen it again if you still experience this problem.

**Closed by piksel** 2018-06-06 10:12 UTC
Labels: awaiting feedback
