### ISSUE TITLE
Ability to create a byte for bype consistent zipfile

### ISSUE THREAD

**Issue by isidore** [icsharpcode/SharpZipLib#81] opened 2015-06-30 09:40 UTC
Right now if I zip up the same things twice. I will end up with 2 different files. There are times where it is beneficial to be able to generate the exact same file.

ps. I would be very happy to pair with someone to solve this problem. I was having problems getting the code to compile, but am sure together this is a 1/2 hour problem max.

**Comment by McNeight** [comment] 2016-04-15 04:13
This is a duplicate of #58. The files are not consistent because of the timestamps not being identical. If you set
```csharp
Entry.DosTime = 0;
```
then the files should be identical.

**Closed by McNeight** 2016-04-15 04:13 UTC
Labels: duplicate, question
