### ISSUE TITLE
ZipOutputStream copy all arborescence

### ISSUE THREAD

**Issue by josselinchevalay** [icsharpcode/SharpZipLib#21] opened 2013-12-03 20:01 UTC
Hi, 

I watched and followed your tutorial download for IIS. 

I have a concern however. The zip file contains the absolute path to the directory or file. I would like to know how it starts specified or recursion.

let me explain:

c:/toto/tutu/MyProject/zip/Project1/*

become : 

Project1/\* 

on Project1.zip

**Comment by piksel** [comment] 2018-09-16 16:59
I am unable to reproduce this, so closing it as it's also really old.

**Closed by piksel** 2018-09-16 16:59 UTC
Labels: iis, question
