### ISSUE TITLE
Undesirable Console log while reading

### ISSUE THREAD

**Issue by PalfLex** [icsharpcode/SharpZipLib#807] opened 2022-12-14 09:50 UTC
### Steps to reproduce
1. It happens every time when the InitialRead method is called.

### Expected behavior
This method should not write information ("Input Encoding:" and "Input Bytes") into the console.

### Actual behavior
Since the new version 1.4.1 (Commit: a389d9f521dc5ddeae575511dc918b22baab22a5;  "fix(zip): cleanup/fix of StringCodec") there those two lines of code (line 577 and 597 in ZipInputStream) which always write into the console log. 

Could you please fix this, or add an variable to disable this console log?

Thanks

### Version of SharpZipLib
Current Version: 1.4.1

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment] 2022-12-14 19:34
Yeah, that was never supposed to be committed. Sorry about that. I'll try to release a new version fairly soon with this removed.

**Comment by PalfLex** [comment] 2022-12-15 06:41
Dear Piksel, thank you very much for answering this fast and for correcting this issue.

**Closed** 2022-12-15 15:10 UTC

**Comment by PalfLex** [comment] 2023-01-04 07:03
Dear Piksel, when are you going to put a new version with the fix online? :)

**Comment by piksel** [comment] 2023-01-04 07:53
There were some concurrency bug when testing in CI, so I put the new release on hold until I could isolate the bug. I have not been able to reproduce it since then, so I am leaning towards ignoring it for now anyway. Sorry for the delay.
