### ISSUE TITLE
WinZipAES256 problem on UWP

### ISSUE THREAD

**Issue by Kutikov** [icsharpcode/SharpZipLib#212] opened 2018-01-30 19:30 UTC
### Steps to reproduce
1. Make UWP project min sdk 10240
2. Create Zip using **WinZipAES256** with some password
3. Try to extract it using ZipFile.GetInputStream(zipEntry)

### Expected behavior
Opening zip file and extracting entries. **WinRAR** opens this file and shows no errors.

### Actual behavior
`System.ArgumentException: Specified initialization vector (IV) does not match the block size for this algorithm.Parameter name: rgbIV   at Internal.Cryptography.AesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)   at Internal.Cryptography.AesImplementation.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)   at ICSharpCode.SharpZipLib.Encryption.ZipAESTransform..ctor(String key, Byte[] saltBytes, Int32 blockSize, Boolean writeMode)   at ICSharpCode.SharpZipLib.Zip.ZipFile.CreateAndInitDecryptionStream(Stream baseStream, ZipEntry entry)   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(Int64 entryIndex)   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)   at damirkutTestsDataGetter.MainPage.ZipDeCrypter(String localfolder, String[] FileNames)`

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [x] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by Messulethe92** [comment] 2018-02-26 08:30
Hi @Kutikov , I experienced the exact same issue. What I did to get around this is to change the input passport to 16 characters, after which I was able to successfully extract the ZIP file.

**Comment by Messulethe92** [comment] 2018-02-27 06:19
After further use, the 16 characters only work for files of a certain size. So the IV is a calculated value, which needs to be done per file. Since a password is usually constant, using Password for IV doesn't make sense. So this is an issue that caused me to look for different unzipping solutions.

**Comment by piksel** [comment] 2018-05-12 16:10
Duplicate of #181

**Closed by piksel** 2018-05-12 16:10 UTC
Labels: bug, encryption, zip
