### ISSUE TITLE
FastZip.ExtractZip only uses WindowsNameTransform.

### ISSUE THREAD

**Issue by mulovad** [icsharpcode/SharpZipLib#61] opened 2014-10-03 08:27 UTC
FastZip works on windows but not on other platform. 
So I checked out the source.
It only uses WindowsNameTransform, so dir\b.txt is saved as filename 'dir\a.txt' as is.
Please fix this.
Anyway. Thank you for the nice library.

**Comment by ermshiperete** [comment] 2015-01-31 21:09
This is a duplicate of #54

**Comment by McNeight** [comment] 2016-04-14 20:24
This issue was resolved when PR #65 was merged into master at e01215507cf25a5978a0bd850c9e67dbabf515b7

-Neil

**Closed by McNeight** 2016-04-14 20:24 UTC
Labels: duplicate
