### ISSUE TITLE
The DLLs in version 1.3.x of the nuget package all target NET45

### ISSUE THREAD

**Issue by afriron** [icsharpcode/SharpZipLib#609] opened 2021-04-07 06:54 UTC
### Steps to reproduce
1. Connect the SharpZipLib package version 1.3.1 to a project with the net core platform.

### Expected behavior
The package connects and works.

### Actual behavior
The package is connected, but it is marked as erroneous in Visual Studio.

If you go to the contents of the package, you can see that the files in the folders `lib\net45` and `lib\netstandard2.0` are absolutely identical.

The ILSpy decompiler shows that for `lib\netstandard2.0\ICSharpCode.SharpZipLib.dll`:
```
Target platform:  NetFramework, Version=v4.5.
```

In version 1.2.0 of the library, everything was correct.

### Version of SharpZipLib
1.3.0, 1.3.1

### Obtained from (only keep the relevant lines)
- Package installed using NuGet

**Comment by piksel** [comment] 2021-04-07 11:49
Confirmed. This was due to the build system overwriting it's own output when using an output path `-o`, so it built the three versions of the dll, each time overwriting it, and then adding those dlls (same file, but being referenced three times) into the final nuget package.

This was fixed in 5ae4f10f564f9459dfbf43fca5873340505c4a53 where the builds where split (latest artifact built from master correctly have different versions for .NET 45 and standard v2.0 and v2.1).

It should probably be mentioned that the NET45 code is there for backwards compatibility, and basically only differs in added polyfills for .NET standard features. That being said, if it doesn't compile/run, then that doesn't matter.

There should be another release fairly soon, or if not, at least a patch-release with a fixed nuget package.

**Comment by piksel** [comment] 2021-05-08 17:26
Fixed in [v1.3.2](https://github.com/icsharpcode/SharpZipLib/releases/tag/v1.3.2)!
![image](https://user-images.githubusercontent.com/807383/117548084-3d1c0800-b033-11eb-87eb-85d1b534694b.png)

**Closed by piksel** 2021-05-08 17:26 UTC
