### ISSUE TITLE
ZipFile.Delete on a folder entry fails

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#48] opened 2013-12-29 17:24 UTC
[SD-1915](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=1915), originally created on 10/10/2012 01:39:29 by David Pierson

ZipFile.Delete on a folder entry fails with an exception.

 The call to FindExistingUpdate changes the name of what is being looked
for and it fails to find the key.

[community.sharpdevelop.net/forums/t/16314.aspx](http://community.sharpdevelop.net/forums/t/16314.aspx)

**Comment by Numpsy** [comment] 2020-10-11 22:25
Is the deleting of folder entries all fixed now?

**Comment by piksel** [comment] 2020-10-13 15:14
It should be. Otherwise a new ticket should be created anyway since the mentioned root cause here should at least not trigger it anymore.

**Closed by piksel** 2020-10-13 15:14 UTC
Labels: bug
