### ISSUE TITLE
Extract archive less then 10Kb.

### ISSUE THREAD

**Issue by olnistratov** [icsharpcode/SharpZipLib#409] opened 2020-01-09 12:59 UTC
### Steps to reproduce
1. Create sample project that can create .tar.gz archive and extract from it. I used examples from
  https://github.com/icsharpcode/SharpZipLib/wiki/GZip-and-Tar-Samples#-simple-full-extract-from-a-tgz-targz
  https://github.com/icsharpcode/SharpZipLib/wiki/GZip-and-Tar-Samples#-create-a-tgz-targz
2. Create test file less than 10Kb. I created .txt file with some data.
3. Create tar.gz archive
4. Try to extract from created archive.

### Expected behavior
The archive will be extracted.
### Actual behavior
There is an error on extraction:

> ICSharpCode.SharpZipLib.GZip.GZipException: 'Error GZIP header, first magic byte doesn't match'

### Version of SharpZipLib
I used SharpZipLib version 1.2.0
[FileLess10Kb.zip](https://github.com/icsharpcode/SharpZipLib/files/4040449/FileLess10Kb.zip)

- Package installed using NuGet

**Comment by piksel** [comment] 2020-01-10 18:22
This sounds like a duplicate of #393. Should be fixed by #390.

**Comment by Numpsy** [comment] 2020-08-17 21:40
Think this should be fixed now?

**Comment by piksel** [comment] 2020-08-18 08:32
Yeah

**Closed by piksel** 2020-08-18 08:32 UTC
Labels: duplicate, gzip
