### ISSUE TITLE
Move library repo from SourceForge

### ISSUE THREAD

**Issue by sbrickey** [icsharpcode/SharpZipLib#79] opened 2015-06-16 14:11 UTC
given their recent decision to meddle with the downloads, please consider moving the assembly downloads. Perhaps a different branch/repo in GH? (similar to ghpages)

Thanks :)

**Comment by McNeight** [comment] 2016-04-15 03:34
I think this does need to happen, but I'm going to close this issue as a duplicate of #75.

**Closed by McNeight** 2016-04-15 03:34 UTC
Labels: duplicate, enhancement, question
